apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: web-rolebinding
 namespace: default
roleRef:
 apiGroup: rbac.authorization.k8s.io
 kind: Role
 name: web-role
subjects:
- kind: User
  name: web-user
  apiGroup: rbac.authorization.k8s.io